
cfg = 'model/configs/retinanet_r50_fpn_1x.py'
model_path = 'model/work_dirs/retinanet_r50_fpn_1x/epoch_12.pth'
cat2label = {
    1: {'name': '一次性快餐盒', 'id': 1, 'supercategory': '其他垃圾'},
    2: {'name': '书籍纸张', 'id': 2, 'supercategory': '可回收物'},
    3: {'name': '充电宝', 'id': 3, 'supercategory': '可回收物'},
    4: {'name': '剩饭剩菜', 'id': 4, 'supercategory': '厨余垃圾'},
    5: {'name': '包', 'id': 5, 'supercategory': '可回收物'},
    6: {'name': '垃圾桶', 'id': 6, 'supercategory': '可回收物'},
    7: {'name': '塑料器皿', 'id': 7, 'supercategory': '可回收物'},
    8: {'name': '塑料玩具', 'id': 8, 'supercategory': '可回收物'},
    9: {'name': '塑料衣架', 'id': 9, 'supercategory': '可回收物'},
    10: {'name': '大骨头', 'id': 10, 'supercategory': '厨余垃圾'},
    11: {'name': '干电池', 'id': 11, 'supercategory': '有害垃圾'},
    12: {'name': '快递纸袋', 'id': 12, 'supercategory': '可回收物'},
    13: {'name': '插头电线', 'id': 13, 'supercategory': '可回收物'},
    14: {'name': '旧衣服', 'id': 14, 'supercategory': '可回收物'},
    15: {'name': '易拉罐', 'id': 15, 'supercategory': '可回收物'},
    16: {'name': '枕头', 'id': 16, 'supercategory': '可回收物'},
    17: {'name': '果皮果肉', 'id': 17, 'supercategory': '厨余垃圾'},
    18: {'name': '毛绒玩具', 'id': 18, 'supercategory': '可回收物'},
    19: {'name': '污损塑料', 'id': 19, 'supercategory': '其他垃圾'},
    20: {'name': '污损用纸', 'id': 20, 'supercategory': '其他垃圾'},
    21: {'name': '洗护用品', 'id': 21, 'supercategory': '可回收物'},
    22: {'name': '烟蒂', 'id': 22, 'supercategory': '其他垃圾'},
    23: {'name': '牙签', 'id': 23, 'supercategory': '其他垃圾'},
    24: {'name': '玻璃器皿', 'id': 24, 'supercategory': '可回收物'},
    25: {'name': '砧板', 'id': 25, 'supercategory': '可回收物'},
    26: {'name': '筷子', 'id': 26, 'supercategory': '其他垃圾'},
    27: {'name': '纸盒纸箱', 'id': 27, 'supercategory': '可回收物'},
    28: {'name': '花盆', 'id': 28, 'supercategory': '其他垃圾'},
    29: {'name': '茶叶渣', 'id': 29, 'supercategory': '厨余垃圾'},
    30: {'name': '菜帮菜叶', 'id': 30, 'supercategory': '厨余垃圾'},
    31: {'name': '蛋壳', 'id': 31, 'supercategory': '厨余垃圾'},
    32: {'name': '调料瓶', 'id': 32, 'supercategory': '可回收物'},
    33: {'name': '软膏', 'id': 33, 'supercategory': '有害垃圾'},
    34: {'name': '过期药物', 'id': 34, 'supercategory': '有害垃圾'},
    35: {'name': '酒瓶', 'id': 35, 'supercategory': '可回收物'},
    36: {'name': '金属厨具', 'id': 36, 'supercategory': '可回收物'},
    37: {'name': '金属器皿', 'id': 37, 'supercategory': '可回收物'},
    38: {'name': '金属食品罐', 'id': 38, 'supercategory': '可回收物'},
    39: {'name': '锅', 'id': 39, 'supercategory': '可回收物'},
    40: {'name': '陶瓷器皿', 'id': 40, 'supercategory': '其他垃圾'},
    41: {'name': '鞋', 'id': 41, 'supercategory': '可回收物'},
    42: {'name': '食用油桶', 'id': 42, 'supercategory': '可回收物'},
    43: {'name': '饮料瓶', 'id': 43, 'supercategory': '可回收物'},
    44: {'name': '鱼骨', 'id': 44, 'supercategory': '厨余垃圾'}
}
